version: "3"
secrets:
  web_password:
    file: ${PWD}/pihole/secrets/web_password.txt
services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    volumes:
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/var/root.hints
        target: /opt/unbound/etc/unbound/var/root.hints
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/unbound.conf
        target: /opt/unbound/etc/unbound/unbound.conf
    restart: always
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    hostname: ${PIHOLEHOSTNAME}.${DOMAIN}.${TLD}
    image: pihole/pihole:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Etc/UTC'
      WEBPASSWORD_FILE: /run/secrets/web_password
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 'unbound#53'
      FTLCONF_LOCAL_IPV4: pihole
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
    secrets:
      - web_password
    volumes:
      - ${PWD}/pihole/etc-pihole:/etc/pihole
      - ${PWD}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
  bind9init:
    depends_on:
      - pihole
    container_name: bind9init
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        while ! ping -c 1 -n pihole >/dev/null 2>&1; do
          echo "Waiting for pihole to become available..."
          sleep 1
        done
        sed "s/EXAMPLE_PIHOLEIP_DOCKER/$(getent hosts pihole | awk '{ print $1 }')/g" /etc/bind/named.conf_example.options > /etc/bind/named.conf.options
    volumes:
      - ${PWD}/bind/etc/bind:/etc/bind
  bind9:
    depends_on:
      bind9init:
        condition: service_completed_successfully
    container_name: bind9
    hostname: ${BIND9HOSTNAME}.${DOMAIN}.${TLD}
    image: ubuntu/bind9:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      BIND9_USER: bind
      TZ: 'Etc/UTC'
    volumes:
      - ${PWD}/bind/etc/bind:/etc/bind
      - ${PWD}/bind/var/cache/bind:/var/cache/bind
    restart: always
