version: "3"
networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/16
          ip_range: 172.31.1.0/24
          gateway: 172.31.1.1
secrets:
  web_password:
    file: ${PWD}/pihole/secrets/web_password.txt
services:
  unbound:
    container_name: unbound
    hostname: unbound1.thetom.xyz
    image: "mvance/unbound:latest"
    volumes:
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/var/root.hints
        target: /opt/unbound/etc/unbound/var/root.hints
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/unbound.conf
        target: /opt/unbound/etc/unbound/unbound.conf
    networks:
      dns:
        ipv4_address: 172.31.1.2
        aliases:
          - unbound1
    restart: always
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    hostname: pihole1.thetom.xyz
    image: pihole/pihole:latest
    networks:
      dns:
        ipv4_address: 172.31.1.3
        aliases:
          - pihole1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Etc/UTC'
      WEBPASSWORD_FILE: /run/secrets/web_password
      DNSMASQ_LISTENING: 'all'
      PIHOLE_DNS_: 'unbound1#53'
      FTLCONF_LOCAL_IPV4: 172.31.1.3
    secrets:
      - web_password
    volumes:
      - ${PWD}/pihole/etc-pihole:/etc/pihole
      - ${PWD}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
  bind9:
    depends_on:
      - pihole
    container_name: bind9
    hostname: dns1.thetom.xyz
    image: ubuntu/bind9:latest
    networks:
      dns:
        ipv4_address: 172.31.1.4
        aliases:
          - dns1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - BIND9_USER=bind
      - TZ=Etc/UTC
    volumes:
      - ${PWD}/bind/etc/bind:/etc/bind
      - ${PWD}/bind/var/cache/bind:/var/cache/bind
    restart: always
