version: "3"
networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}/${SUBNETCIDR}
          ip_range: ${IPRANGE}/${IPRANGECIDR}
          gateway: ${GATEWAY}
secrets:
  web_password:
    file: ${PWD}/pihole/secrets/web_password.txt
services:
  unbound:
    container_name: unbound
    hostname: ${UNBOUNDHOSTNAME}.${DOMAIN}.${TLD}
    image: mvance/unbound:latest
    volumes:
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/var/root.hints
        target: /opt/unbound/etc/unbound/var/root.hints
      - type: bind
        read_only: true
        source: ${PWD}/unbound/etc/unbound/unbound.conf
        target: /opt/unbound/etc/unbound/unbound.conf
    networks:
      dns:
        ipv4_address: ${UNBOUNDIP}
        aliases:
          - ${UNBOUNDHOSTNAME}
    restart: always
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    hostname: ${PIHOLEHOSTNAME}.${DOMAIN}.${TLD}
    image: pihole/pihole:latest
    networks:
      dns:
        ipv4_address: ${PIHOLEIP}
        aliases:
          - ${PIHOLEHOSTNAME}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Etc/UTC'
      WEBPASSWORD_FILE: /run/secrets/web_password
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 'unbound1#53'
      FTLCONF_LOCAL_IPV4: ${BIND9IP}
    secrets:
      - web_password
    volumes:
      - ${PWD}/pihole/etc-pihole:/etc/pihole
      - ${PWD}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
  bind9:
    depends_on:
      - pihole
    container_name: bind9
    hostname: ${BIND9HOSTNAME}.${DOMAIN}.${TLD}
    image: ubuntu/bind9:latest
    networks:
      dns:
        ipv4_address: ${BIND9IP}
        aliases:
          - ${BIND9HOSTNAME}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      BIND9_USER: bind
      TZ: 'Etc/UTC'
    volumes:
      - ${PWD}/bind/etc/bind:/etc/bind
      - ${PWD}/bind/var/cache/bind:/var/cache/bind
    restart: always
